### ISSUE TITLE
nil icon name when dashboard-set-heading-icons turned on

### ISSUE THREAD

**Issue by sunng87** [emacs-dashboard/emacs-dashboard#459]
When `dashboard-set-heading-icons` turned on, I'm getting error: `unable to find icon with name nil in icon set` with both nerd-icons and all-the-icons. Not sure if it's because additional headings in dashboard-widgets like ls-directory.

**Comment by jcs090218** [comment]
What's the value of your variable `dashboard-icon-type`? It should either be ``all-the-icons` or `'nerd-icons`.

**Comment by sunng87** [comment]
I've tested with both all-the-icons and nerd-icons, the error persists until I turned off heading icons and keeps only file icons. So I believe it has something to do with heading icon set.

**Comment by mikaelspringer** [comment]
I experience the same thing. When I set `dashboard-set-heading-icons` to `t`, I get the error message and no icons are shown in `*dashboard*`. When I set `dashboard-set-heading-icons` to `nil`, the error message disappear and icons are shown again in *dashboard*.

One other strange thing is that when I do `M-x customize-group dashboard` a lot of the icon related variables are marked `CHANGED outside Customize. (mismatch)`. I know for sure I haven't changed them.

**Comment by jcs090218** [comment]
What's the value of variable `dashboard-heading-icons`? It seems like it's nil and it shouldn't be. 🤔 

It could be an issue regarding the order you load this package, it should be something similar to:

```elisp
(setq dashboard-set-heading-icons t)
(require 'dashboard)  ; it will auto configure it for you
```

or set them all manually:

```elisp
(require 'dashboard)
(setq dashboard-set-heading-icons t)
(setq dashboard-icon-type 'all-the-icons)
(setq dashboard-heading-icons '((recents   . "history")
                                (bookmarks . "bookmark")
                                (agenda    . "calendar")
                                (projects  . "rocket")
                                (registers . "database")))
```

**Comment by sunng87** [comment]
After checking `customize-variable`, I found `dashboard-heading-icons` is set to `nil`.

**Comment by knaveightt** [comment]
Hello everyone - will also raise that I am experiencing the same issue. After reviewing this thread, I also tried to set the icons manually as well, but to no avail. Here is the exact config I am using, utilizing use-package for reference. Willing to try alternative approaches based on feedback:

```emacs-lisp
  (use-package dashboard
    :config
    (dashboard-setup-startup-hook)
    (setq dashboard-items '((recents  . 5)
			    (bookmarks . 5)
			    (projects . 5)
			    (agenda . 5)
			    (registers . 5)))
    (setq dashboard-set-heading-icons t)
    (setq dashboard-icon-type 'all-the-icons)
    (setq dashboard-heading-icons '((recents   . "history")
                                    (bookmarks . "bookmark")
                                    (agenda    . "calendar")
                                    (projects  . "rocket")
                                    (registers . "database"))))  
```

**Comment by jcs090218** [comment]
Hi, @knaveightt! What kind of error did you get? It seems like you configure the package correctly. 🤔

**Comment by knaveightt** [comment]
Hi @jcs090218 ! Before setting the dashboard-heading-icons manually, I was also receiving the `unable to find icon with name nil in icon set` error that @sunng87 received too. Once setting the dashboard-heading-icons manually, I no longer received the error message, but still no icons showed in the dashboard :(
![screenshot](https://github.com/emacs-dashboard/emacs-dashboard/assets/2282100/d1058bf7-455b-4a04-9045-94c7c030ea87)

**Comment by jcs090218** [comment]
The insertion logic is here:

https://github.com/emacs-dashboard/emacs-dashboard/blob/34a0076f01a729b4aae16947fa0d0e130cafedfd/dashboard-widgets.el#L582

Do your environment support icons? Are you using a terminal? 🤔

**Comment by ricardoricho** [comment]
Hi @knaveightt your config looks good, I checked the code and there are [some](https://github.com/emacs-dashboard/emacs-dashboard/blob/34a0076f01a729b4aae16947fa0d0e130cafedfd/dashboard-widgets.el#L144) evaluations at loading time (maybe we have to fix [that](https://github.com/emacs-dashboard/emacs-dashboard/blob/34a0076f01a729b4aae16947fa0d0e130cafedfd/dashboard-widgets.el#L163)).
Moving the setting of icons variables to the `init` could fix the problem.
```emacs-lisp
  (use-package dashboard
    :config
    (dashboard-setup-startup-hook)
    :init
    (setq dashboard-items '((recents  . 5)
			    (bookmarks . 5)
			    (projects . 5)
			    (agenda . 5)
			    (registers . 5)))
    (setq dashboard-set-heading-icons t)
    (setq dashboard-set-file-icons t)
    (setq dashboard-icon-type 'all-the-icons)
    (setq dashboard-heading-icons '((recents   . "history")
                                    (bookmarks . "bookmark")
                                    (agenda    . "calendar")
                                    (projects  . "rocket")
                                    (registers . "database"))))  
```
Please, let me know if that works.  Maybe you have to add `(require 'all-the-icons)` or with `(use-package all-the-icons :demand t)`

**Comment by xenobis** [comment]
Hi all,

if you still have problems displaying icons for headers and files, etc., please have a look at my pull request #467. As long as it is not merged into the master, you can simply replace the file "dashboard-widgets.el" in the package folder "dashboard-20230512.1839" with the same file from the pull request. You also have to delete the corresponding *.elc file, e.g. "dashboard-widgets.elc", so that the changes have an impact.

**Comment by team-epk** [comment]
I was having this issue, and I was able to fix it by changing two lines in dashboard-widget.el
```
(defcustom dashboard-set-heading-icons t ;; this used to say "nil"
  "When non nil, heading sections will have icons."
  :type 'boolean
  :group 'dashboard)

(defcustom dashboard-set-file-icons t ;; this also used to say "nil"
  "When non nil, file lists will have icons."
  :type 'boolean
  :group 'dashboard)

```
Whether or not this is a good idea, I don't know. But this is where it seemed to be getting the idea that something was nil, and nothing I did to my init.el seemed to work. This did.

**Comment by seagle0128** [comment]
My workaround: 
```elisp
(advice-add #'dashboard-replace-displayable :override #'identity)
```

**Comment by LukeDRussell** [comment]
I've been having the same problem for a while. I *think* I've got a fix. The proposed fixes above didn't help me.

Essentially, I've moved the customizations (i.e. `setq`) into use-package's :custom section. Before this change, I had all the variables being set under :config.

```elisp
(use-package dashboard
    :config
        (dashboard-setup-startup-hook)
    :custom
        (dashboard-startup-banner 'logo)
        (dashboard-banner-logo-title nil)
        (dashboard-center-content t)
        (dashboard-icon-type 'nerd-icons)
        (dashboard-set-heading-icons t)
        (dashboard-set-file-icons t)
        (dashboard-set-footer nil)
        (dashboard-projects-backend 'project-el)
        (dashboard-display-icons-p t)
        (dashboard-items '(
            (recents . 5)
            (agenda . 5)
            (projects . 5)
            (bookmarks . 5)
)))

```
![Screenshot from 2023-11-15 20-20-39](https://github.com/emacs-dashboard/emacs-dashboard/assets/6735465/27fe0403-4bc1-4654-b76b-1a96ab785ed3)

Forgive me for getting any of the terms incorrect, I'm an emacs newbie.

**Comment by seagle0128** [comment]
I think it has been fixed in https://github.com/emacs-dashboard/emacs-dashboard/commit/3fce60c285ed4d22a00d6f5b49335d038aa9cd41.

**Comment by LukeDRussell** [comment]
It was still broken for me in the last week, until I moved the config into `:custom` section.

**Comment by knaveightt** [comment]
Hi All - I entered this thread back around May, and just recently tried @LukeDRussell's suggestion (as well as recently moving from all-the-icons to nerd-icons for my setup). It seems to work now for me!

**Comment by jonBoone** [comment]
FYI, I'm using dash.el 2.20.0 through `use-package` and `straight`.  I am able to get the icons to work properly with:

``` elisp
(use-package dashboard
  :straight t
  :init
  (setq dashboard-display-icons-p    t
        dashboard-icon-type          'nerd-icons
        dashboard-set-file-icons     t
        dashboard-set-headings-icons t)
  :config
  (dashboard-setup-startup-hook))
```

**Comment by christophermadsen** [comment]
> I've been having the same problem for a while. I _think_ I've got a fix. The proposed fixes above didn't help me.
> 
> Essentially, I've moved the customizations (i.e. `setq`) into use-package's :custom section. Before this change, I had all the variables being set under :config - just like the folks above.
> 
> ```emacs-lisp
> (use-package dashboard
>     :config
>         (dashboard-setup-startup-hook)
>     :custom
>         (dashboard-startup-banner 'logo)
>         (dashboard-banner-logo-title nil)
>         (dashboard-center-content t)
>         (dashboard-icon-type 'nerd-icons)
>         (dashboard-set-heading-icons t)
>         (dashboard-set-file-icons t)
>         (dashboard-set-footer nil)
>         (dashboard-projects-backend 'project-el)
>         (dashboard-display-icons-p t)
>         (dashboard-items '(
>             (recents . 5)
>             (agenda . 5)
>             (projects . 5)
>             (bookmarks . 5)
> )))
> ```

Moving the icon statements to the `:custom` keyword fixes it for me as well.
Windows 10
Emacs 29.1

My dashboard.el config
```emacs-lisp
(use-package dashboard
  :ensure t
  :config
  (dashboard-setup-startup-hook)
  :diminish
  (dashboard-mode page-break-lines-mode)
  :custom
  (dashboard-center-content t)
  (dashboard-startup-banner 4)
  (dashboard-items '((recents . 10)))
  (dashboard-icon-type 'nerd-icons)
  (dashboard-set-heading-icons t)
  (dashboard-set-file-icons t)
  :custom-face
  (dashboard-heading ((t (:foreground "#f1fa8c" :weight bold))))
  :hook
  (after-init . dashboard-setup-startup-hook))

(setq initial-buffer-choice (lambda () (get-buffer-create "*dashboard*")))
(setq dashboard-banner-logo-title "Aah, you're back. Drink your coffee while it's warm . . .")
(setq dashboard-startup-banner "~/.emacs.d/coffee-isometric-dashboard.png")
```

And here's a final image of what the icons look like.
![image](https://github.com/emacs-dashboard/emacs-dashboard/assets/39905290/ad92eecd-8aed-480b-b8cd-a4e02f9f2908)

**Comment by rosstimson** [comment]
I'd tried a bunch of 'fixes' for this over the months to no avail, @christophermadsen's suggestion to shift everything into `:custom` is what finally did the trick.  Many thanks.

**Comment by christophermadsen** [comment]
> I'd tried a bunch of 'fixes' for this over the months to no avail, @christophermadsen's suggestion to shift everything into `:custom` is what finally did the trick. Many thanks.

Really happy it's also fixed for you! But it was @LukeDRussell who came up with the solution :)

**Comment by igorcafe** [comment]
I guess it may have something to do with running emacs  as a daemon?

**Comment by cena** [comment]
Just as another data point, I switched from Elpaca to use-package and my icons, formerly working, stopped with the `nable to find icon with name nil in icon set` error.

Moving my previous (setq...)s to `:custom` resolved the issue.
